-- Seed data for local development
-- Run after all migrations: psql $DATABASE_URL -f supabase/seed.sql

-- ── Test project ──────────────────────────────────────────────────────────────

INSERT INTO projects (id, name, slug, status, stack, repo_url)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'Кофейня "Зерно"',
  'kofeynaya-zerno',
  'active',
  '{"framework": "next", "css": "tailwind", "language": "typescript"}',
  NULL
);

-- ── Context docs ─────────────────────────────────────────────────────────────

INSERT INTO context_docs (project_id, doc_type, title, content)
VALUES
  (
    '00000000-0000-0000-0000-000000000001',
    'brief',
    'Бриф проекта',
    'Небольшая кофейня в центре города. Нужен сайт-визитка с меню, историей и формой брони столика. Аудитория — молодые профессионалы 25-35 лет. Стиль: уютный, минималистичный, тёплые тона.'
  ),
  (
    '00000000-0000-0000-0000-000000000001',
    'styleguide',
    'Стайлгайд',
    'Цвета: primary=#3D2B1F (тёмный кофе), accent=#C8956C (карамель), bg=#FAF7F2 (сливки). Шрифты: заголовки — Playfair Display, текст — Inter. Скругления — lg (8px). Без жёстких теней.'
  );

-- ── Test task ────────────────────────────────────────────────────────────────

INSERT INTO tasks (id, project_id, type, status, input, source, claude_model)
VALUES (
  '00000000-0000-0000-0000-000000000002',
  '00000000-0000-0000-0000-000000000001',
  'design',
  'done',
  '{"request": "Главная страница: hero с фото, секция меню, форма брони"}',
  'telegram',
  'sonnet'
);

-- ── Design version ───────────────────────────────────────────────────────────

INSERT INTO design_versions (task_id, project_id, version, variant, html_code, status)
VALUES (
  '00000000-0000-0000-0000-000000000002',
  '00000000-0000-0000-0000-000000000001',
  1,
  1,
  '<!-- placeholder: design HTML will be generated by DesignPipeline -->',
  'pending'
);

-- ── Conversation history ─────────────────────────────────────────────────────

INSERT INTO conversation_history (project_id, task_id, role, content, source)
VALUES
  (
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000002',
    'user',
    'Сделай главную страницу для кофейни. Хочу hero с большим фото, ниже меню и форму для брони столика.',
    'telegram'
  ),
  (
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000002',
    'assistant',
    'Понял! Генерирую дизайн главной страницы кофейни "Зерно". Добавлю hero-блок с атмосферным фото, раздел с популярными позициями меню и форму бронирования столика. Используем тёплую палитру из стайлгайда.',
    'telegram'
  );

-- ── Project plan ─────────────────────────────────────────────────────────────

INSERT INTO project_plans (project_id, version, plan, status, mode)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  1,
  '{
    "brief": "Сайт-визитка кофейни: меню, история, форма брони столика",
    "phases": [
      {
        "id": "phase-1",
        "title": "Дизайн",
        "type": "design",
        "checkpoint": true,
        "tasks": [
          {
            "id": "task-1-1",
            "title": "Главная страница",
            "description": "Hero + меню + форма брони",
            "type": "design",
            "status": "done",
            "estimatedMinutes": 10,
            "dependsOn": []
          },
          {
            "id": "task-1-2",
            "title": "Страница меню",
            "description": "Полное меню с категориями и фото",
            "type": "design",
            "status": "pending",
            "estimatedMinutes": 8,
            "dependsOn": ["task-1-1"]
          }
        ]
      },
      {
        "id": "phase-2",
        "title": "Код",
        "type": "code",
        "checkpoint": true,
        "tasks": [
          {
            "id": "task-2-1",
            "title": "Next.js проект",
            "description": "Инициализация, layout, компоненты",
            "type": "code",
            "status": "pending",
            "estimatedMinutes": 20,
            "dependsOn": ["task-1-1", "task-1-2"]
          }
        ]
      },
      {
        "id": "phase-3",
        "title": "Деплой",
        "type": "deploy",
        "checkpoint": false,
        "tasks": [
          {
            "id": "task-3-1",
            "title": "Деплой на Vercel",
            "description": "Публикация и настройка домена",
            "type": "deploy",
            "status": "pending",
            "estimatedMinutes": 5,
            "dependsOn": ["task-2-1"]
          }
        ]
      }
    ],
    "currentPhaseIndex": 0
  }',
  'active',
  'autopilot'
);
